// A small in-memory stand-in for @anthropic-ai/sdk, used by the page-writer
// example so it runs anywhere with no API key. It returns a generated HTML
// document and logs the call — it is deliberately a mock, not a real client.
// Swap the import for "@anthropic-ai/sdk" to call the real model.

function escapeHtml(value: string): string {
  const entities: Record<string, string> = { "&": "&amp;", "<": "&lt;", ">": "&gt;" };
  return value.replace(/[&<>]/g, (char) => entities[char] ?? char);
}

class Anthropic {
  messages = {
    create: async (
      request: Anthropic.MessageCreateParamsNonStreaming,
    ): Promise<{ content: Array<{ type: string; text: string }> }> => {
      const prompt = request.messages.map((message) => message.content).join(" ");
      console.log(`[mock Anthropic] messages.create — "${prompt.slice(0, 60)}"`);
      const title = escapeHtml(prompt);
      const html =
        `<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n` +
        `    <title>${title}</title>\n  </head>\n  <body>\n    <main>\n` +
        `      <h1>${title}</h1>\n      <p>Generated by the example mock model.</p>\n` +
        `    </main>\n  </body>\n</html>`;
      return { content: [{ type: "text", text: html }] };
    },
  };
}

namespace Anthropic {
  export interface MessageCreateParamsNonStreaming {
    model: string;
    max_tokens: number;
    system?: string;
    messages: Array<{ role: string; content: string }>;
  }
}

export default Anthropic;
