name: Build Pipeline Binary

on:
  push:
    branches: [ main ]
    paths:
      - "go/**"
      - ".github/workflows/build_pipeline_binary.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: go/go.sum

      - name: Build pipeline binary
        working-directory: go
        run: make build

      - name: Upload pipeline binary
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-binary
          path: go/bin
