name: Deploy Escambo Stack

on:
  workflow_dispatch:
    inputs:
      stack:
        description: "Name of the stack to deploy (e.g. escambo-dev-customer-react-web-client)"
        required: true
      resumeUrl:
        description: "N8N Webhook URL to resume workflow"
        required: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Install CDKTF dependencies
        run: npm ci

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: CDKTF Get
        run: npx cdktf get

      - name: Deploy Stack
        run: npx cdktf deploy ${{ github.event.inputs.stack }} --auto-approve

      - name: Resume N8N workflow
        if: ${{ github.event.inputs.resumeUrl != '' && always() }}
        run: |
          curl -X POST "${{ github.event.inputs.resumeUrl }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"status\": \"${{ job.status }}\",
              \"stack\": \"${{ github.event.inputs.stack }}\",
              \"run_id\": \"${{ github.run_id }}\",
              \"repository\": \"${{ github.repository }}\"
            }"
