name: Build Docker

on:
  push:
    branches: [ main ]
    paths:
      - .github/docker/Dockerfile
      - .github/workflows/docker.yml
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/docker/Dockerfile
          push: true
          tags: ghcr.io/escambo-me/ruby-aws-terraform:latest
