name: Run Pipeline

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Build Pipeline Binaries"]
    types: [completed]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

        run: npm ci

      # Download compiled Go binaries
      - name: Download backend binary
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GH_PAT_TOKEN }}
          workflow: build_pipeline_binaries.yml
          name: backend-binary
          path: ./bin

      - name: Download deploy binary
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GH_PAT_TOKEN }}
          workflow: build_pipeline_binaries.yml
          name: deploy-binary
          path: ./bin

      - name: Make binaries executable
        run: chmod +x ./bin/backend ./bin/deploy

      - name: Run backend setup
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        run: ./bin/backend

      - name: Run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
        run: ./bin/deploy
